Imports

In [40]:
# Librerías que se necesitaron
import pandas as pd

Links analyst

In [41]:
# Analisis de la estructura del link.
# https://www.football-data.co.uk/mmz4281/2223/E0.csv: "https://www.football-data.co.uk/mmz4281/" + "2223" + "/" + "E0" + ".csv"

# Nomenglatura de ligas: England
# Premier League (FT & HT results; match stats; match, total goals & AH odds) / E0
# Championship (FT & HT results; match stats; match, total goals & AH odds) / E1
# League 1 (FT & HT results; match stats; match, total goals & AH odds) / E2
# League 2 (FT & HT results; match stats; match, total goals & AH odds) / E3

# Analisis de la estructura del link.
# https://www.football-data.co.uk/mmz4281/2223/E0.csv: "https://www.football-data.co.uk/mmz4281/" + "2223" + "/" + "SC0" + ".csv"

# Nomenglatura de ligas: Scotland
# Premier League (FT & HT results; match stats; match, total goals & AH odds) / SC0
# Division 1 (FT & HT results; match stats; match, total goals & AH odds) / SC1
# Division 2 (FT & HT results; match stats; match, total goals & AH odds) / SC2
# Division 3 (FT & HT results; match stats; match, total goals & AH odds) / SC3

# Analisis de la estructura del link. 
# https://www.football-data.co.uk/mmz4281/2223/E0.csv: "https://www.football-data.co.uk/mmz4281/" + "2223" + "/" + "D1" + ".csv"

# Nomenglatura de ligas: Germany
# Bundesliga 1 (FT & HT results; match stats; match, total goals & AH odds) / D1
# Bundesliga 2 (FT & HT results; match stats; match, total goals, & AH odds) / D2

# Analisis de la estructura del link.
# https://www.football-data.co.uk/mmz4281/2223/E0.csv: "https://www.football-data.co.uk/mmz4281/" + "2223" + "/" + "I1" + ".csv"

# Nomenglatura de ligas: Italy
# Serie A (FT & HT results; match stats; match, total goals & AH odds) / I1
# Serie B (FT & HT results; match stats; match odds and total goals odds) / I2

#### Note: From 2018/2019 the shots data for Serie A is showing an inconsistency with previous seasons, and looks to be related 
### to the inclusion of blocked shots. Users of the data should bear this in mind when collating several seasons together for analysis purposes.

# Analisis de la estructura del link.
# https://www.football-data.co.uk/mmz4281/2223/E0.csv: "https://www.football-data.co.uk/mmz4281/" + "2223" + "/" + "SP1" + ".csv"

# Nomenglatura de ligas: Spain
# La Liga Primera Division (FT & HT results; match stats; match, total goals & AH odds) / SP1
# La Liga Segunda Division (FT & HT results; match stats; match odds and total goals odds) / SP2

# Analisis de la estructura del link.
# https://www.football-data.co.uk/mmz4281/2223/E0.csv: "https://www.football-data.co.uk/mmz4281/" + "2223" + "/" + "F1" + ".csv"

# Nomenglatura de ligas: France
# Le Championnant (FT & HT results; match stats; match, total goals & AH odds) / F1
# Division 2 (FT & HT results; match stats; match odds and total goals odds) / F2

# Analisis de la estructura del link.
# https://www.football-data.co.uk/mmz4281/2223/E0.csv: "https://www.football-data.co.uk/mmz4281/" + "2223" + "/" + "N1" + ".csv"

# Nomenglatura de ligas: Netherlands
# Eredivisie (FT & HT results; match stats; match, total goals & AH odds) / F1

# Analisis de la estructura del link.
# https://www.football-data.co.uk/mmz4281/2223/E0.csv: "https://www.football-data.co.uk/mmz4281/" + "2223" + "/" + "B1" + ".csv"

# Nomenglatura de ligas: Belgium
# Jupiler League (FT & HT results; match stats; match, total goals & AH odds) / B1

# Analisis de la estructura del link.
# https://www.football-data.co.uk/mmz4281/2223/E0.csv: "https://www.football-data.co.uk/mmz4281/" + "2223" + "/" + "P1" + ".csv"

# Nomenglatura de ligas: Portugal
# Liga I (FT & HT results; match stats; match, total goals & AH odds) / P1

# Analisis de la estructura del link.
# https://www.football-data.co.uk/mmz4281/2223/E0.csv: "https://www.football-data.co.uk/mmz4281/" + "2223" + "/" + "T1" + ".csv"

# Nomenglatura de ligas: Turkey
# Futbol Ligi 1 (FT & HT results; match stats; match, total goals & AH odds) / T1

# Analisis de la estructura del link.
# https://www.football-data.co.uk/mmz4281/2223/E0.csv: "https://www.football-data.co.uk/mmz4281/" + "2223" + "/" + "G1" + ".csv"

# Nomenglatura de ligas: Greece
# Ethniki Katigoria (FT & HT results; match stats; match, total goals & AH odds) / G1

Code for web scrapping

In [42]:
# Declaramos una variable root con la parte del enlace que no cambia.
root = "https://www.football-data.co.uk/mmz4281/"

In [43]:
# Listas para almancenar las ligas
leagues = ['E0', 'E1', 'E2', 'E3', # England
           'SC0', 'SC1', 'SC2', 'SC3', # Scotland
            'D1', 'D2', # Germany
            'I1', 'I2', # Italy
            'SP1', 'SP2', # Spain
            'F1', 'F2', # France
            'N1', # Netherlands
            'B1', # Belgium
            'P1', # Portugal
            'T1', # Turkey
            'G1' # Greece
           ]

# Diccionario para renombrar en la columna del dataframe
league_to_country = {'E0': 'England',
                     'E1': 'England',
                     'E2': 'England',
                     'E3': 'England',
                     'SC0': 'Scotland',
                     'SC1': 'Scotland',
                     'SC2': 'Scotland',
                     'SC3': 'Scotland',
                     'D1': 'Germany',
                     'D2': 'Germany',
                     'I1': 'Italy',
                     'I2': 'Italy',
                     'SP1': 'Spain',
                     'SP2': 'Spain',
                     'F1': 'France',
                     'F2': 'France',
                     'N1': 'Netherlands',
                     'B1': 'Belgium',
                     'P1': 'Portugal',
                     'T1': 'Turkey',
                     'G1': 'Greece'
                    }



alleuro = [] # Aquí se almacenarán los nuevos data frames


# Ciclo para leer los multiples cvs y adjuntarlos.
for league in leagues:

    for season in range(10, 23): # Rango para contar las ligas: 10+1 = 1011

        df = pd.read_csv(root + str(season) + str(season+1) + '/' + league + '.csv', encoding='unicode_escape')
        df.insert(1, 'Season', season) # Inserto una columna llamada season
        df.rename(columns={'Div': 'League'}, inplace=True) # Se renombra a la columna div por League

        
        df['Country'] = df['League'].map(league_to_country) # Se utiliza el diccionario para renombrar los codigos de ligas
        df.insert(0, 'Country', df.pop('Country')) # Se inserta la columna Country

        # Necesitaba borrar muchas columnas que no me aportaban nada, mantuve solo las que necesito.
        # Despues en el reporte borraré otras cuantas pero las mantendré en el CSV original por si gustan revisarlo.
        columnas_mantener = ['Date', 'Season', 'League', 'Country', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HHW', 'AHW', 'HC', 'AC', 'HF', 'AF', 'HO', 'AO', 'HY', 'AY', 'HR', 'AR', 'HBP', 'ABP']
        df.drop(columns=[col for col in df.columns if col not in columnas_mantener], inplace=True)


        #-----------------------------------------------------------------------------#
        # En este aparto se llamo a los DF y se les suplanto con su respectiva liga.
        #-----------------------------------------------------------------------------#

        # England
        df['League'].replace('E0', 'Premier League', inplace=True)
        df['League'].replace('E1', 'Championship', inplace=True)
        df['League'].replace('E2', 'League 1', inplace=True)
        df['League'].replace('E3', 'League 2', inplace=True)

        # Scotland
        df['League'].replace('SC0', 'Premier League', inplace=True)
        df['League'].replace('SC1', 'Division 1', inplace=True)
        df['League'].replace('SC2', 'Division 2', inplace=True)
        df['League'].replace('SC3', 'Division 3', inplace=True)

        # Germany
        df['League'].replace('D1', 'Bundesliga 1', inplace=True)
        df['League'].replace('D2', 'Bundesliga 2', inplace=True)

        # Italy
        df['League'].replace('I1', 'Seria A', inplace=True)
        df['League'].replace('I2', 'Serie B', inplace=True)

        # Spain
        df['League'].replace('SP1', 'La Liga 1', inplace=True)
        df['League'].replace('SP2', 'La Liga 2', inplace=True)

        # France
        df['League'].replace('F1', 'Le Championnant', inplace=True)
        df['League'].replace('F2', 'Division 2', inplace=True)

        # Netherlands
        df['League'].replace('N1', 'Eredivisie', inplace=True)

        # Belgium
        df['League'].replace('B1', 'Jupiler', inplace=True)

        # Portugal
        df['League'].replace('P1', 'Liga I', inplace=True)

        # Turkey
        df['League'].replace('T1', 'Ligi 1', inplace=True)

        # Greece
        df['League'].replace('G1', 'Ethniki Katigoria', inplace=True)
        #-----------------------------------------------------------------------------#

        alleuro.append(df) # Forma de almacenar los DF que se van a iterar en frames.

In [44]:
len(alleuro) # A modo de revisión siempre se necesita corroborar la totalidad de tus datos

273

In [45]:
alleuro[272] # Revisamos que funcione la lista (0-272)

,Country,League,Season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,Greece,Ethniki Katigoria,22,19/08/2022,Volos NFC,Asteras Tripolis,3,3,D,1,...,6,4,12,18,3,3,4,3,0,0
1,Greece,Ethniki Katigoria,22,20/08/2022,Atromitos,OFI Crete,3,1,H,2,...,4,2,9,20,2,5,2,4,0,0
2,Greece,Ethniki Katigoria,22,20/08/2022,Lamia,AEK,0,3,A,0,...,2,3,16,18,0,1,1,1,0,0
3,Greece,Ethniki Katigoria,22,20/08/2022,PAOK,Panetolikos,1,0,H,1,...,7,2,12,9,7,4,0,2,0,0
4,Greece,Ethniki Katigoria,22,21/08/2022,Panathinaikos,Ionikos,1,0,H,1,...,4,1,11,18,6,1,1,4,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,Greece,Ethniki Katigoria,22,13/05/2023,Ionikos,Lamia,2,2,D,2,...,4,6,21,15,7,2,3,5,0,0
236,Greece,Ethniki Katigoria,22,13/05/2023,Levadeiakos,Giannina,3,3,D,2,...,12,4,14,16,13,2,0,2,0,0
237,Greece,Ethniki Katigoria,22,14/05/2023,AEK,Volos NFC,4,0,H,2,...,8,0,14,4,5,0,0,0,0,0
238,Greece,Ethniki Katigoria,22,14/05/2023,Panathinaikos,Aris,1,1,D,1,...,5,4,15,16,4,3,1,3,0,0
239,Greece,Ethniki Katigoria,22,14/05/2023,PAOK,Olympiakos,0,1,A,0,...,6,4,11,13,3,3,2,1,0,0

In [46]:
total_filas = 0
for df in alleuro:
    total_filas += df.shape[0]
print(total_filas)

# Quería saber el número de filas, lol.

93397

In [47]:
# Para facilitar el reporte voy a concatenar todos los archivos CSV que metimos en la lista alleuro[] y la exportaré
# como un solo archivo CSV.

concatenated_df = pd.concat(alleuro)

# Exporta el DataFrame concatenado a un archivo csv
concatenated_df.to_csv('data_futbol_20102023.csv', index=False)

Clean data

In [48]:
# En este apartado voy a necesitar borrar muchas filas incompletas pues me he dado cuenta que no todos 
# los archivos que descargamos tienen toda la información necesaria. Apartir de aquí, este analisis se vuelve
# meramente practico, ya que al borrar datos y no determinar rangos iguales en cuanto cantidad, me veo forzado
# a desfasar un poco el resultado del analisis. De todas maneras, sirve para el fin de este proyecto: practicar.

In [49]:
# Leemos el archivo que generamos y lo nombramos df para facilidad.
df = pd.read_csv('data_futbol_20102023.csv', low_memory=False)

In [50]:
# La función dropna y subset nos ayudan a verificar que esas columnas con el HOW = any, eliminen de estas, las que no esten completas.
df = df.dropna(subset=['Date', 'Season', 'League', 'Country', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HC', 'AC', 'HF', 'AF', 'HY', 'AY', 'HR', 'AR'], how='any')

In [51]:
# Nuevo archivo csv limpiado
df.to_csv('clean_data_futbol_20102023.csv', index=False)